// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  project_images: dynamic(() => import("./ProjectImages")),
  year_item: dynamic(() => import("./YearItem")),
};
